# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fighting Futility
email: JamesB.fe80@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Incarnation something of my useless attempt to run a blog. If I can't
  even manage to bang out a Facebook post a year what chance does this
  have of being viable.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JamesB192.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  JamesB192

# Build settings
markdown: kramdown
timezone: America/Los_Angeles
safe: true
